"3:50pm. Trying to add the folder and it fails.
Uah.

4pm. https://stackoverflow.com/questions/50849365/debug-in-python-library-with-visual-studio

This is much like my own question.

4:05pm. Ok, I can verify that breakpoints inside libraries work, but not the step functions. If I go inside `make` using a breakpoint and then step, it goes straight out.

What is going on here?

Is this supposed to be standard behavior?

Maybe I do not to put more effort into setting up VS Code. Forget VS for a bit.

4:10pm. VS Code just crashes for some dumb reason when I try to step into `env.make`.

I have no idea...

Maybe I could try another IDE?

Let me try PyCharm.

4:15pm. Ugh...setting up tools is the worst part of the whole programming business.

4:20pm. Maybe I should just go back to working on Spiral?

I am kidding, but that is exactly what is going to happen if I cannot resolve this issue. Python already impresses with its reliability.

Let me reboot.

4:40pm.

```
Exception ignored in: <bound method Viewer.__del__ of <gym.envs.classic_control.rendering.Viewer object at 0x000002464D81A160>>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\gym\envs\classic_control\rendering.py", line 143, in __del__
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\gym\envs\classic_control\rendering.py", line 62, in close
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\pyglet\window\win32\__init__.py", line 305, in close
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\pyglet\window\__init__.py", line 770, in close
ImportError: sys.meta_path is None, Python is likely shutting down
```

I thought I got it to work, but now I am getting this exception.

Damn.

4:45pm. For some reason the environment has a tendency to return done as True and False at random so I cannot use that in order to break out of a update. That variable rather than being about the game being over is probably about the step being over...like a hand of poker rather than the betting round.

And this error seems to be `pyglet` related.

https://pyglet.readthedocs.io/en/pyglet-1.3-maintenance/programming_guide/installation.html

This thing seems to be interesting.

4:55pm. I am thinking about transformations I could do to make Spiral more efficient. This time I am how I could fuse closures.

Yeah, it would not be too hard.

One by one, as I think the problems with making an efficient implementation seem to be going away and I would not even have to drop down into C.

5pm. I have the same issue with pyglet as I do with the gym examples. This is good as it means I will be able to get closer to figuring out what the problem is here.

5:10pm. Ogh, now why won't `go to definition` work on `pyglet`.

I hate when it just does not work for no reason sometimes. Fuck it, seriously.

...Ah, reseting the VS IDE makes it work all of a sudden.

5:15pm. Now I am trying to grip with how to download the Pyglet documentation. It is not in the source directory and I have no idea how to get it from Bitbucket without having to download some shitty program.

https://bitbucket.org/pyglet/pyglet/downloads/

Oh, it is here.

6pm. Done with lunch. Girly Air Force is a drop. Asuka that I watched during the previous break was good just as expected though. I already liked the manga - too bad the scanlations has stalled.

6:05pm.

```
import pyglet

window = pyglet.window.Window()
label = pyglet.text.Label('Hello, world',
                          font_name='Times New Roman',
                          font_size=36,
                          x=window.width//2, y=window.height//2,
                          anchor_x='center', anchor_y='center')

@window.event
def on_draw():
    window.clear()
    label.draw()

pyglet.app.run()
```

Surprisingly this piece of code works without a hitch.

Thinking back to the OpenAI code that I saw, I am surprised they use raw pixels as output measure. I know that WPF eschews that in favor of ratios. They already has some issues due to this.

Let me read the documentation for a bit more and then I will call it day.

6:25pm.

```
import pyglet

window = pyglet.window.Window()
label = pyglet.text.Label('Hello, world',
                          font_name='Times New Roman',
                          font_size=36,
                          x=window.width//2, y=window.height//2,
                          anchor_x='center', anchor_y='center')

@window.event
def on_draw():
    window.clear()
    label.draw()

pyglet.app.run()
```

I hate how this just locks up the application. Isn't there a better way of doing this?

6:30pm. https://pyglet.readthedocs.io/en/pyglet-1.3-maintenance/programming_guide/graphics.html

I am supposed to be reading this, but I just keep thinking of how to do the Spiral prepass and the right way to compile pattern matching.

6:45pm. https://pyglet.readthedocs.io/en/pyglet-1.3-maintenance/programming_guide/eventloop.html

This is so annoying. If I can't customize the event loop that means it will lock the interpreter every time I run it. Isn't there a way to do message passing so as to allow live editing?

7pm. Let me call it a day here. I am more interested in the Spiral prepass anyway.

7:10pm. I really want to go for longer, but I should not strain myself.

7:15pm. Yeah, it is really embarrassing how much I accomplished today.

I did figure out `DeBruijin` to do indexing properly in the background and how it would be much better that would be than using `PersistentVector`, but I really should be figuring out how to do RL in Python instead.

I am not sure what my goals are here to be honest.

What are my goals? A good question.

I need to figure how to make plotting and such async. That should be my first priority.

How about I go for a change of pace. Instead of wrestling with Pyglets, how about I do GUIs tomorrow? It has been a while since I did it last. If I can figure out how to GUIs properly I could probably figure out how to do the rest properly as well.

I want to avoid the fate of doing literally every single thing from the command line. GUIs and REPL should lead the way forward."